import { useEffect, useState, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import type { SolvedProblem, FilterState, Difficulty } from "./types";
import { selectRandom, extractAllTopics, filterProblems } from "./utils/selectRandom";
import { loadUserData, saveUserData, clearUserData } from "./utils/storage";
import { playTick, playLand } from "./utils/sound";

type SpinPhase = "idle" | "spinning" | "landing";

function App() {
  const [allProblems, setAllProblems] = useState<SolvedProblem[]>([]);
  const [problems, setProblems] = useState<SolvedProblem[]>([]);
  const [current, setCurrent] = useState<SolvedProblem | null>(null);
  const [lastId, setLastId] = useState<string | null>(null);
  const [topics, setTopics] = useState<string[]>([]);
  const [phase, setPhase] = useState<SpinPhase>("idle");
  const [key, setKey] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [showInfo, setShowInfo] = useState(false);
  const [showClearConfirm, setShowClearConfirm] = useState(false);
  const [isDemoMode, setIsDemoMode] = useState(true);
  const [openDropdown, setOpenDropdown] = useState<string | null>(null);

  const [filters, setFilters] = useState<FilterState>({
    difficulties: [],
    topics: [],
    prioritizeUnseen: false,
  });

  const [loading, setLoading] = useState(true);
  const statsRef = useRef<Map<string, { times_shown: number; last_shown: string | null }>>(new Map());

  // Load Initial Data
  const loadDefaultData = useCallback(() => {
    setLoading(true);
    fetch("/data/all_problems.json")
      .then((r) => r.json())
      .then((data: SolvedProblem[]) => {
        setAllProblems(data);
        setTopics(extractAllTopics(data));
        setIsDemoMode(true);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  useEffect(() => {
    const customData = loadUserData();
    if (customData) {
      setAllProblems(customData);
      setTopics(extractAllTopics(customData));
      setIsDemoMode(false);
      setLoading(false);
    } else {
      loadDefaultData();
    }
  }, [loadDefaultData]);

  useEffect(() => {
    setProblems(filterProblems(allProblems, filters.difficulties, filters.topics));
  }, [allProblems, filters]);

  // Close dropdown on outside click
  useEffect(() => {
    if (!openDropdown) return;
    const handler = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest(".dropdown")) {
        setOpenDropdown(null);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [openDropdown]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        if (Array.isArray(parsed) && parsed.length > 0 && parsed[0].questionId) {
          saveUserData(parsed);
          setAllProblems(parsed);
          setTopics(extractAllTopics(parsed));
          setIsDemoMode(false);
          setShowSettings(false);
          setCurrent(null);
        } else {
          alert("Invalid file format. Ensure it's the JSON array generated by the script.");
        }
      } catch (err) {
        alert("Failed to parse JSON file.");
      }
    };
    reader.readAsText(file);
    e.target.value = ''; // reset input
  };

  const handleClearData = () => {
    setShowClearConfirm(true);
  };

  const confirmClear = () => {
    clearUserData();
    setCurrent(null);
    loadDefaultData();
    setShowSettings(false);
    setShowClearConfirm(false);
  };

  const withStats = useCallback(
    (p: SolvedProblem): SolvedProblem => {
      const s = statsRef.current.get(p.questionId);
      return s ? { ...p, ...s } : p;
    },
    []
  );

  const enriched = useCallback(
    () =>
      problems.map((p) => {
        const s = statsRef.current.get(p.questionId);
        return s ? { ...p, ...s } : p;
      }),
    [problems]
  );

  const spin = useCallback(() => {
    if (problems.length === 0 || phase !== "idle") return;

    const final = selectRandom(enriched(), lastId, filters.prioritizeUnseen);
    if (!final) return;

    setPhase("spinning");
    let tick = 0;
    const total = 16;
    let delay = 45;

    const next = () => {
      tick++;
      // Pitch rises as we slow down (0→1)
      const progress = tick / total;
      playTick(progress * 0.6);

      if (tick >= total) {
        const ex = statsRef.current.get(final.questionId) ?? {
          times_shown: final.times_shown,
          last_shown: final.last_shown,
        };
        statsRef.current.set(final.questionId, {
          times_shown: ex.times_shown + 1,
          last_shown: new Date().toISOString(),
        });
        setCurrent(withStats(final));
        setLastId(final.questionId);
        setKey((k) => k + 1);
        setPhase("landing");
        playLand();
        setTimeout(() => setPhase("idle"), 600);
      } else {
        setCurrent(problems[Math.floor(Math.random() * problems.length)]);
        setKey((k) => k + 1);
        // Exponential slow-down: starts fast, slows dramatically
        delay *= 1.12 + progress * 0.12;
        setTimeout(next, delay);
      }
    };

    playTick(0);
    setCurrent(problems[Math.floor(Math.random() * problems.length)]);
    setKey((k) => k + 1);
    setTimeout(next, delay);
  }, [problems, lastId, filters.prioritizeUnseen, phase, enriched, withStats]);

  // Framer Motion
  const variants = {
    initial: { y: 60, opacity: 0, filter: "blur(8px)" },
    animate: { y: 0, opacity: 1, filter: "blur(0px)" },
    exit: { y: -60, opacity: 0, filter: "blur(8px)" },
  };

  const transition =
    phase === "landing"
      ? { type: "spring" as const, stiffness: 80, damping: 14, mass: 1 }
      : { duration: 0.12, ease: [0.25, 0.1, 0.25, 1] as const };

  const diffLabel = current
    ? current.difficulty.toUpperCase() +
      (current.topics.length > 0 ? ` · ${current.topics[0].toUpperCase()}` : "")
    : "";

  return (
    <>
      <div className="mesh" />

      <div className="shell">
        {/* Header */}
        <div className="header">
          <div className="logo">LeetRoulette</div>
          
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginTop: '-6px', fontSize: '0.75rem', color: 'var(--text-dim)' }}>
            made by
            <a 
              href="https://instagram.com/deepxkrana" 
              target="_blank" 
              rel="noopener noreferrer" 
              style={{ 
                display: 'flex', alignItems: 'center', gap: '4px', 
                padding: '4px 10px', borderRadius: '100px', 
                border: '1px solid var(--border)', color: 'var(--text)', 
                textDecoration: 'none', background: 'rgba(255,255,255,0.02)', 
                transition: 'background 0.2s',
                fontFamily: 'var(--sans)'
              }}
              onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.06)'}
              onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.02)'}
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
              </svg>
              @deepxkrana
            </a>
          </div>

          <div style={{ fontSize: "0.7rem", color: isDemoMode ? "var(--accent)" : "#4ade80", letterSpacing: "0.05em", textTransform: "uppercase", marginTop: "4px" }}>
            {isDemoMode ? "All Questions Mode" : "Custom Mode"}
          </div>
          <div className="filter-row" style={{ marginTop: "8px", display: "flex", gap: "8px" }}>
            {/* Difficulty Dropdown */}
            <div className="dropdown">
              <button
                className={`dropdown-trigger ${openDropdown === "diff" ? "open" : ""}`}
                onClick={() => setOpenDropdown(openDropdown === "diff" ? null : "diff")}
              >
                {filters.difficulties[0] || "All Difficulties"}
                <span className="dropdown-chevron">▼</span>
              </button>
              <AnimatePresence>
                {openDropdown === "diff" && (
                  <motion.div
                    className="dropdown-panel"
                    initial={{ opacity: 0, y: -8, scale: 0.96 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: -8, scale: 0.96 }}
                    transition={{ duration: 0.15, ease: "easeOut" }}
                  >
                    {["", "Easy", "Medium", "Hard"].map((d) => (
                      <button
                        key={d || "all"}
                        className={`dropdown-item ${(filters.difficulties[0] || "") === d ? "active" : ""}`}
                        onClick={() => {
                          setFilters((f) => ({ ...f, difficulties: d ? [d as Difficulty] : [] }));
                          setOpenDropdown(null);
                        }}
                      >
                        {d || "All Difficulties"}
                      </button>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Topics Dropdown */}
            <div className="dropdown">
              <button
                className={`dropdown-trigger ${openDropdown === "topic" ? "open" : ""}`}
                onClick={() => setOpenDropdown(openDropdown === "topic" ? null : "topic")}
              >
                {filters.topics[0] || "All Topics"}
                <span className="dropdown-chevron">▼</span>
              </button>
              <AnimatePresence>
                {openDropdown === "topic" && (
                  <motion.div
                    className="dropdown-panel"
                    initial={{ opacity: 0, y: -8, scale: 0.96 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: -8, scale: 0.96 }}
                    transition={{ duration: 0.15, ease: "easeOut" }}
                  >
                    <button
                      className={`dropdown-item ${filters.topics.length === 0 ? "active" : ""}`}
                      onClick={() => {
                        setFilters((f) => ({ ...f, topics: [] }));
                        setOpenDropdown(null);
                      }}
                    >
                      All Topics
                    </button>
                    {topics.map((t) => (
                      <button
                        key={t}
                        className={`dropdown-item ${filters.topics[0] === t ? "active" : ""}`}
                        onClick={() => {
                          setFilters((f) => ({ ...f, topics: [t] }));
                          setOpenDropdown(null);
                        }}
                      >
                        {t}
                      </button>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>

        {/* Display */}
        <div className="display">
          <div className="viewport">
            <AnimatePresence mode="popLayout">
              {loading ? (
                <motion.div key="load" className="frame" {...variants} transition={{ duration: 0.3 }}>
                  <div className="label">LOADING</div>
                  <div className="title" style={{ fontSize: "2.5rem" }}>...</div>
                </motion.div>
              ) : problems.length === 0 ? (
                <motion.div key="empty" className="frame" {...variants} transition={{ duration: 0.3 }}>
                  <div className="label">NO MATCHES</div>
                  <div className="title" style={{ fontSize: "2.5rem" }}>Adjust filters</div>
                </motion.div>
              ) : !current ? (
                <motion.div key="ready" className="frame" {...variants} transition={{ duration: 0.4 }}>
                  <div className="label">READY</div>
                  <div className="title">Spin the wheel</div>
                </motion.div>
              ) : (
                <motion.div
                  key={key}
                  className="frame"
                  initial={variants.initial}
                  animate={variants.animate}
                  exit={variants.exit}
                  transition={transition}
                >
                  <div className="label">{diffLabel}</div>
                  <h2 className="title">{current.title}</h2>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        {/* Bottom */}
        <div className="controls">
          <button className="btn-spin" onClick={spin} disabled={loading || problems.length === 0 || phase !== "idle"}>
            {current ? "Spin again" : "Spin"}
          </button>

          <AnimatePresence>
            {current && phase === "idle" && (
              <motion.a
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ duration: 0.2 }}
                href={current.leetcode_url}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-link"
              >
                Solve on LeetCode
              </motion.a>
            )}
          </AnimatePresence>

          <button className="btn-icon" onClick={() => setShowSettings(true)} aria-label="Settings">
            ⚙
          </button>
          <button className="btn-icon" onClick={() => setShowInfo(true)} aria-label="Info">
            ⓘ
          </button>
        </div>
      </div>

      {/* Settings drawer */}
      <AnimatePresence>
        {showSettings && (
          <>
            <motion.div
              className="drawer-overlay"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowSettings(false)}
            />
            <motion.div
              className="drawer"
              initial={{ y: "100%" }}
              animate={{ y: 0 }}
              exit={{ y: "100%" }}
              transition={{ type: "spring", stiffness: 300, damping: 30 }}
            >
              <div className="drawer-handle" />
              <div className="drawer-title" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                Settings
                {isDemoMode ? (
                  <span style={{ fontSize: '0.75rem', background: 'rgba(255,255,255,0.1)', padding: '4px 8px', borderRadius: '4px' }}>All Questions Mode</span>
                ) : (
                  <span style={{ fontSize: '0.75rem', background: 'rgba(34, 197, 94, 0.2)', color: '#4ade80', padding: '4px 8px', borderRadius: '4px' }}>Custom Data Active</span>
                )}
              </div>

              <div className="drawer-row">
                <span className="drawer-label">Prioritize unseen problems</span>
                <button
                  className={`toggle ${filters.prioritizeUnseen ? "on" : ""}`}
                  onClick={() => setFilters((f) => ({ ...f, prioritizeUnseen: !f.prioritizeUnseen }))}
                >
                  <div className="toggle-knob" />
                </button>
              </div>

              <div className="drawer-row">
                <span className="drawer-label">Problems in pool</span>
                <span style={{ fontWeight: 600, fontSize: "0.85rem" }}>
                  {problems.length} / {allProblems.length}
                </span>
              </div>

              <div style={{ height: '1px', background: 'var(--border)', margin: '12px 0' }} />

              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                <div style={{ fontSize: '0.9rem', fontWeight: 600 }}>Your LeetCode Data</div>
                
                {isDemoMode ? (
                  <>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-dim)', lineHeight: 1.5 }}>
                      You are currently viewing All Questions Mode. To use your own solved problems:
                    </p>
                    <ol style={{ fontSize: '0.75rem', color: 'var(--text-dim)', lineHeight: 1.6, paddingLeft: '20px', margin: 0 }}>
                      <li>Go to <a href="https://leetcode.com" target="_blank" rel="noreferrer" style={{ color: 'var(--accent)' }}>leetcode.com</a> and log in.</li>
                      <li>Open Developer Tools (F12) ➔ Console.</li>
                      <li>Paste <a href="/extract_leetcode.js" target="_blank" rel="noreferrer" style={{ color: 'var(--accent)' }}>this extraction script</a> and hit Enter.</li>
                      <li>Upload the downloaded JSON file below!</li>
                    </ol>
                    <label style={{
                      display: 'flex', justifyContent: 'center', alignItems: 'center',
                      padding: '16px', border: '1px dashed var(--border)', borderRadius: '12px',
                      cursor: 'pointer', fontSize: '0.85rem', color: 'var(--text)',
                      background: 'rgba(255,255,255,0.02)', transition: 'background 0.2s', marginTop: '8px'
                    }}>
                      Click to upload your JSON file
                      <input type="file" accept=".json" style={{ display: 'none' }} onChange={handleFileUpload} />
                    </label>
                  </>
                ) : (
                  <div style={{ display: 'flex', gap: '12px' }}>
                    <label style={{
                      flex: 1, padding: '10px', border: '1px solid var(--border)', borderRadius: '8px',
                      cursor: 'pointer', fontSize: '0.8rem', color: 'var(--text)', textAlign: 'center',
                      background: 'rgba(255,255,255,0.02)'
                    }}>
                      Upload new data
                      <input type="file" accept=".json" style={{ display: 'none' }} onChange={handleFileUpload} />
                    </label>
                    <button 
                      onClick={handleClearData}
                      style={{
                        flex: 1, padding: '10px', border: '1px solid rgba(255, 0, 0, 0.3)', borderRadius: '8px',
                        cursor: 'pointer', fontSize: '0.8rem', color: '#ff6b6b', textAlign: 'center',
                        background: 'rgba(255, 0, 0, 0.05)'
                      }}>
                      Clear Data (All Questions Mode)
                    </button>
                  </div>
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Info drawer */}
      <AnimatePresence>
        {showInfo && (
          <>
            <motion.div
              className="drawer-overlay"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowInfo(false)}
            />
            <motion.div
              className="drawer"
              initial={{ y: "100%" }}
              animate={{ y: 0 }}
              exit={{ y: "100%" }}
              transition={{ type: "spring", stiffness: 300, damping: 30 }}
            >
              <div className="drawer-handle" />
              <div className="drawer-title" style={{ fontSize: '1.4rem', color: 'var(--accent)' }}>About LeetRoulette</div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', color: 'var(--text-dim)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                <p>
                  <strong>LeetRoulette</strong> is a minimalist tool to help you pick LeetCode problems at random.
                </p>
                <p>
                  By default, it loads all 4,000+ public questions from LeetCode. You can filter the pool by <strong>Difficulty</strong> or specific <strong>Topics</strong> using the dropdowns at the top.
                </p>
                <p>
                  <strong style={{ color: 'var(--text)' }}>Want to practice your own solved problems?</strong><br/>
                  Click the Settings icon (⚙) to find instructions on how to generate and upload a JSON file containing only your personal LeetCode history. Once uploaded, your data stays saved in your browser locally!
                </p>
                <p>
                  <strong style={{ color: 'var(--text)' }}>Prioritize unseen problems:</strong><br/>
                  When enabled in settings, the wheel will heavily favor problems it hasn't landed on yet during this session, helping you cycle through your backlog.
                </p>
                <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'center' }}>
                  <a 
                    href="https://github.com/deepxkrana" 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    style={{ 
                      display: 'flex', alignItems: 'center', gap: '6px', 
                      padding: '6px 12px', borderRadius: '8px', 
                      color: 'var(--text)', textDecoration: 'none', 
                      background: 'rgba(255,255,255,0.03)', 
                      transition: 'background 0.2s',
                      fontSize: '0.85rem'
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.08)'}
                    onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.03)'}
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
                    </svg>
                    @deepxkrana
                  </a>
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Clear Confirmation Modal */}
      <AnimatePresence>
        {showClearConfirm && (
          <motion.div
            className="drawer-overlay"
            style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setShowClearConfirm(false)}
          >
            <motion.div
              onClick={(e) => e.stopPropagation()}
              initial={{ opacity: 0, scale: 0.95, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 10 }}
              transition={{ duration: 0.2, ease: "easeOut" }}
              style={{
                background: '#1a1d1b',
                border: '1px solid var(--border)',
                borderRadius: '16px',
                padding: '24px',
                width: '90%',
                maxWidth: '400px',
                boxShadow: '0 20px 40px rgba(0,0,0,0.5)',
                display: 'flex',
                flexDirection: 'column',
                gap: '16px'
              }}
            >
              <div style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--text)' }}>
                Clear local data?
              </div>
              <div style={{ fontSize: '0.9rem', color: 'var(--text-dim)', lineHeight: 1.5 }}>
                Are you sure you want to clear your uploaded LeetCode history and return to All Questions Mode? You'll need to upload a new JSON file to use your custom data again.
              </div>
              <div style={{ display: 'flex', gap: '12px', marginTop: '8px' }}>
                <button 
                  onClick={() => setShowClearConfirm(false)}
                  style={{
                    flex: 1, padding: '10px', borderRadius: '8px',
                    cursor: 'pointer', fontSize: '0.9rem', color: 'var(--text)',
                    background: 'rgba(255,255,255,0.05)', border: 'none',
                    fontFamily: 'var(--sans)', fontWeight: 500
                  }}>
                  Cancel
                </button>
                <button 
                  onClick={confirmClear}
                  style={{
                    flex: 1, padding: '10px', borderRadius: '8px',
                    cursor: 'pointer', fontSize: '0.9rem', color: '#ff6b6b',
                    background: 'rgba(255, 0, 0, 0.1)', border: 'none',
                    fontFamily: 'var(--sans)', fontWeight: 500
                  }}>
                  Clear Data
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

export default App;

